name: aqi_monitor
description: "A Flutter AQI monitoring application with space theme and real-time air quality data."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Map and Location Services
  google_maps_flutter: ^2.9.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  
  # HTTP and API
  http: ^1.2.2
  
  # State Management
  provider: ^6.1.2
  
  # UI Components and Animations
  shimmer: ^3.0.0
  animated_text_kit: ^4.2.2
  flutter_svg: ^2.0.10+1
  
  # Charts and Data Visualization
  fl_chart: ^0.69.0
  
  # Weather and Icons
  weather_icons: ^3.0.0
  
  # Utilities
  intl: ^0.19.0
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  
  # Material Design
  cupertino_icons: ^1.0.8

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
  adaptive_icon_background: "#0A043C"
  adaptive_icon_foreground: "assets/logo.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/India-map.svg
    - assets/astronaut.webp
    
  # Uncomment and customize fonts if needed
  # fonts:
  #   - family: SpaceFont
  #     fonts:
  #       - asset: fonts/SpaceFont-Regular.ttf
  #       - asset: fonts/SpaceFont-Bold.ttf
  #         weight: 700
